#!/usr/bin/env bash
#Fix it by copying content from sites available to sites enabled
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
echo '9791' | sudo tee /run/nginx.pid
